name: CI
on: [push, pull_request]
jobs:
  build-Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
    - name: Build
      run: for file in `find ./ -type f -name "*.sln"`; do dotnet build $file; done
    - name: Tests
      run: for file in `find ./ -type f -name "*.sln"`; do dotnet test $file; done
  build-Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
    - name: Build
      run: Foreach($file in (dir -Path ./ -Filter *.sln -Recurse | %{$_.FullName})) { dotnet build $file }
    - name: Tests
      run: Foreach($file in (dir -Path ./ -Filter *.sln -Recurse | %{$_.FullName})) { dotnet test $file }
